config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tv_shows
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tracked_shows, only: [:create, :index]
  resources :watched_shows, only: [:create]
  resources :watched_seasons, only: [:create, :destroy]
  resources :watched_episodes, only: [:create, :destroy]
  resources :calendar, only: [:index]
  
  root 'pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'search' => 'search#index'
  get 'password_resets/new'
  get 'password_resets/edit'
end

app/models/tv_show.rb
class TvShow < ActiveRecord::Base
  has_many :tv_show_relationships
  has_many :users, :through => :tv_show_relationships
  has_many :seasons
  has_many :episodes

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

  def tracked?(current_user)
    tv_show_relationship = self.tv_show_relationships.where(user_id: current_user).first
    tv_show_relationship ? tv_show_relationship.tracked == true : false
  end

  def watched?(current_user)
    tv_show_relationship = self.tv_show_relationships.where(user_id: current_user).first
    tv_show_relationship ? tv_show_relationship.watched == true : false
  end

  def latest_episode(current_user)
    @latest_episode = nil 
            
    self.seasons.reverse.each do |season| 
      season.episodes.reverse.each do |episode|
        @latest_episode = episode unless episode.watched?(current_user)
      end
    end

    @latest_episode = self.seasons.first.episodes.first if @latest_episode.nil?
    return @latest_episode
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: [:show, :edit, :update, :destroy]

  def index
    @tv_shows = TvShow.search(params[:query])
  end

  # GET /tv_shows/1
  # GET /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows
  # POST /tv_shows.json
  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully created.' }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1
  # PATCH/PUT /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1
  # DELETE /tv_shows/1.json
  def destroy
    @tv_show.destroy
    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: 'Tv show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_show_params
      params.require(:tv_show).permit(:name, :created_by, :season, :episodes, :first_air_date, :last_air_date, :overview, :poster_path, :status, :rating, :votes)
    end
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/tv_shows/_form.html.erb
<%= form_for(@tv_show) do |f| %>
  <% if @tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
      <% @tv_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :no_of_seasons %><br>
    <%= f.number_field :no_of_seasons %>
  </div>
  <div class="field">
    <%= f.label :no_of_episodes %><br>
    <%= f.number_field :no_of_episodes %>
  </div>
  <div class="field">
    <%= f.label :first_air_date %><br>
    <%= f.date_select :first_air_date %>
  </div>
  <div class="field">
    <%= f.label :last_air_date %><br>
    <%= f.date_select :last_air_date %>
  </div>
  <div class="field">
    <%= f.label :overview %><br>
    <%= f.text_area :overview %>
  </div>
  <div class="field">
    <%= f.label :poster_path %><br>
    <%= f.text_field :poster_path %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :votes %><br>
    <%= f.number_field :votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Editing Tv Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @tv_shows.count %> TV Shows Found</h1>

<table class="table">
  <tbody>
    <% @tv_shows.each do |tv_show| %>
      <tr>
        <td width="200"><%= image_tag(tv_show.poster_path.nil? ? "https://cdn.amctheatres.com/Media/Default/Images/noposter.jpg" : tv_show.poster_path, size: "150x200") %></td>
        <td>
          <h3><%= link_to tv_show.name, tv_show %></h3>
          <% if not tv_show.tracked?(current_user) %>
            <%= link_to 'Track', tracked_shows_path(:tv_show => tv_show), :method => :post, class: "btn btn-primary btn-watch" %>
          <% else %>
            <%= link_to 'Tracking', tracked_shows_path(:tv_show => tv_show), :method => :post, class: "btn btn-success btn-watch" %>
          <% end %>
          <br />

          <strong>Created By:</strong> <%= tv_show.created_by %><br />
          <strong>Seasons:</strong> <%= tv_show.no_of_seasons %>  <strong>Episodes:</strong> <%= tv_show.no_of_episodes %><br />
          <strong>Status:</strong> <%= tv_show.status %><br />
          <strong>Rating:</strong> <%= tv_show.rating %>  <strong>Votes:</strong> <%= tv_show.votes %><br />

          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_tv_show_path(tv_show) %> |
            <%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
        <td class="vert-align">
          <% if not tv_show.watched?(current_user) %>
            <%= link_to 'Watch', watched_shows_path(:tv_show => tv_show), :method => :post, class: "btn btn-primary btn-watch" %>
          <% else %>
            <%= link_to 'Watching', watched_shows_path(:tv_show => tv_show), :method => :post, class: "btn btn-success btn-watch" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tv_shows/new.html.erb
<h1>New Tv Show</h1>

<%= render 'form' %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<table class="table">
  <tr>
    <td width="200">
      <%= image_tag(@tv_show.poster_path.nil? ? "https://cdn.amctheatres.com/Media/Default/Images/noposter.jpg" : @tv_show.poster_path, size: "150x200") %>
    </td>
    <td>
      <h1>
        <%= @tv_show.name %>
        <% if not @tv_show.tracked?(current_user) %>
          <%= link_to 'Track', tracked_shows_path(:tv_show => @tv_show), :method => :post, class: "btn btn-primary btn-watch" %>
        <% else %>
          <%= link_to 'Tracking', tracked_shows_path(:tv_show => @tv_show), :method => :post, class: "btn btn-success btn-watch" %>
        <% end %>
      </h1>
      <br />
      <strong>Created By:</strong> <%= @tv_show.created_by %><br />
      <strong>Seasons:</strong> <%= @tv_show.no_of_seasons %>  <strong>Episodes:</strong> <%= @tv_show.no_of_episodes %><br />
      <strong>Status:</strong> <%= @tv_show.status %><br />
      <strong>Rating:</strong> <%= @tv_show.rating %>  <strong>Votes:</strong> <%= @tv_show.votes %><br />
    </td>
    <td class="vert-align">
    <% if not @tv_show.watched?(current_user) %>
      <%= link_to 'Watch', watched_shows_path(:tv_show => @tv_show), :method => :post, class: "btn btn-primary btn-watch" %>
    <% else %>
      <%= link_to 'Watched', watched_shows_path(:tv_show => @tv_show), :method => :post, class: "btn btn-success btn-watch" %>
    <% end %>
    </td>
  </tr>
</table>
<br />
<h1>Overview</h1>
<p><%= @tv_show.overview %></p>

<% if current_user.admin? %>
  <%= link_to 'Edit', edit_tv_show_path(@tv_show) %> |
  <%= link_to 'Destroy', @tv_show, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<br />
<h1>Seasons</h1>

<div class="panel-group" id="seasonAccordion" role="tablist" aria-multiselectable="true">
  <% @tv_show.seasons.reverse.each do |season| %>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="seasonHeading<%= season.season_number %>">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#seasonAccordion" href="#seasonCollapse<%= season.season_number %>" aria-expanded="false" aria-controls="seasonCollapse<%= season.season_number %>">
          <div class="row">
            <div class="col-xs-8 col-md-11"><%= season.name %></div> 
            <div class="col-xs-1 col-md-1">
              <% if not season.watched?(current_user) %>
                <%= link_to 'Watch', watched_seasons_path(:season => season), :method => :post, class: "btn btn-primary" %>
              <% else %>
                <%= link_to 'Watched', watched_season_path(season: season), method: :delete, class: "btn btn-success" %>
              <% end %>
            </div>  
          </div>
        </a>
      </h4>
    </div>
    <div id="seasonCollapse<%= season.season_number %>" class="panel-collapse collapse" role="tabpanel" 
         aria-labelledby="seasonHeading<%= season.season_number %>">
      <div class="panel-body">
        <div class="panel-group" id="episodeAccordion<%= season.season_number %>" role="tablist" aria-multiselectable="true">
          <% season.episodes.each do |episode| %>
          <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="episodeHeading<%= season.season_number %><%= episode.episode_number %>">
            <h4 class="panel-title">
              <a class="collapsed" data-toggle="collapse" data-parent="#episodeAccordion<%= season.season_number %>" 
                 href="#episodeCollapse<%= season.season_number %><%= episode.episode_number %>" aria-expanded="false" 
                 aria-controls="episodeCollapse<%= season.season_number %><%= episode.episode_number %>">
              <div class="row">
                <div class="col-xs-8 col-md-11"><%= episode.name %></div> 
                <div class="col-xs-1 col-md-1">
                <% if not episode.watched?(current_user) %>
                  <%= link_to 'Watch', watched_episodes_path(:episode => episode), :method => :post, class: "btn btn-primary" %>
                <% else %>
                  <%= link_to 'Watched', watched_episode_path(:episode => episode), :method => :post, class: "btn btn-success" %>
                <% end %>
                </div>  
              </div>
              </a>
            </h4>
           </div>
           <div id="episodeCollapse<%= season.season_number %><%= episode.episode_number %>" class="panel-collapse collapse" role="tabpanel" 
                aria-labelledby="episodeHeading<%= season.season_number %><%= episode.episode_number %>">
             <div class="panel-body">
               <div class="row">
                 <div class="col-xs-3 col-md-3"> 
                   <%= image_tag(episode.still_path.nil? ? "http://www.motorolasolutions.com/web/Business/Products/Accessories/_Images/ImageNotAvailable/_StaticFiles/ImageNotAvailable_LG.jpg" : episode.still_path, size: "200x125") %></div>
                 <div class="col-xs-8 col-md-8"><%= episode.overview %></div>   
               </div>
             </div>
           </div>
          </div>
          <% end %>
        </div>
        </div>
    </div>
  </div>
  <% end %>
</div>