config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tv_shows
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :tracked_shows, only: [:create, :index]
  resources :watched_shows, only: [:create]
  resources :watched_seasons, only: [:create, :destroy]
  resources :watched_episodes, only: [:create, :destroy]
  resources :calendar, only: [:index]
  
  root 'pages#home'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'search' => 'search#index'
  get 'password_resets/new'
  get 'password_resets/edit'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trackerman</title>
    <%= stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div id="logo">Trackerman</div>
        <% if logged_in? %>
          <nav>
            <div class="ajust-height">
            <ul class="nav navbar-nav pull-right">
              <li>
                <%= link_to calendar_index_path do %>
                  <i class="glyphicon glyphicon-calendar" title="Calendar"></i>
                <% end %>
              </li>
              <li>
                <%= link_to tracked_shows_path do %>
                  <i class="glyphicon glyphicon-play" title="Shows"></i>
                <% end %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="glyphicon glyphicon-user" title="Profile"></i><b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>       
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log Out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            </ul>
            </div>

            <div class="col-sm-3 col-md-3 pull-right">
              <%= form_tag(tv_shows_path, :method => "get", class: "navbar-form") do %>
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search" name="query" id="query">
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
                </div>
              <% end %>
            </div>
          </nav>
        <% end %>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>